name: Deploy Hugo site

env:
  WC_HUGO_VERSION: '0.136.5'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.WC_HUGO_VERSION }}
        extended: true

    - uses: actions/cache@v3
      with:
        path: /tmp/hugo_cache_runner/
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-

    - name: Build the site
      run: |
        echo "Building the Hugo site..."
        hugo --minify

    - name: List contents of public directory (debugging)
      run: |
        echo "Listing contents of public directory"
        ls -la ./public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true  # Ensures a clean deployment

    - name: Confirm Deployment (debugging)
      run: |
        echo "Confirming deployment to GitHub Pages"
        curl -s https://api.github.com/repos/${{ github.repository }}/pages